# swin_base_config:
#   patch_size: [4, 4]
#   embed_dim: 96
#   depths: [2, 2, 18, 2]
#   num_heads: [3, 6, 12, 24]
#   window_size: [7, 7]
#   mlp_ratio: 4.0
#   dropout: 0.0
#   attention_dropout: 0.0
#   stochastic_depth_prob: 0.1
#   num_classes: 1296

# op_flow: False

model_args:
  model: swin_small
  use_bn: 1
  share_classifier: True
  weight_norm: True
  conv_type: 2
  hidden_size: 1024
  num_classes: 1296

training:
  epochs: 50
  batch_size: 2
  clip_grad: False
  device: 0,1

optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  step: [20, 35]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False

data:
  path: /path/to/PHOENIX-2014
  gloss_dict_path: /home/g202302610/Code/OpFlow-SLR/datasets/phoenix2014/gloss_dict.npy
  dataset_name: phoenix14
  dataset_root: /home/g202302610/Code/OpFlow-SLR/datasets/phoenix2014
